FROM almalinux:9

RUN dnf install -y epel-release && \
    dnf install -y \
        gcc gcc-c++ make git patch \
        python3 python3-devel \
        openssl-devel libpng-devel \
        rpm-build rpmdevtools \
        curl tar gzip && \
    curl -fsSL https://rpm.nodesource.com/setup_24.x | bash - && \
    dnf install -y nodejs && \
    npm install -g yarn && \
    dnf clean all

WORKDIR /build
